# Generated by Django 4.1.1 on 2022-09-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_NFT', models.CharField(max_length=30)),
                ('artist_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='./En_af_tee/')),
                ('detail', models.CharField(max_length=500)),
                ('currency', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=500)),
                ('rating', models.IntegerField(default=4)),
            ],
        ),
    ]
